### ISSUE TITLE
conformance with current SHACL spec

### ISSUE THREAD

**Issue by d0rg0ld** [fekaputra/shacl-plugin#14]
Hi there,

is your plugin conforming to the current SHACL spec from https://www.w3.org/TR/shacl/ ?

Thanks and kind regards,
Doron

**Comment by fekaputra** [comment]
Hi,

Unfortunately no, we haven’t got time to work on it after our paper submission back then.

Best regards,
--
Fajar J. Ekaputra
194/1 Information & Software Engineering Group,
Technische Universität Wien (TUWien).
W: http://juang.id Skype: fajar.juang

On 24.05.2018, at 17:03, Doron Goldfarb <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

is your plugin conforming to the current SHACL spec from https://www.w3.org/TR/shacl/ ?

Thanks and kind regards,
Doron

**Comment by d0rg0ld** [comment]
Hi there,

thanks for your quick reply, of course I understand the circumstances. How much effort do you think would it be to update the code accordingly?

Kind regards,
Doron

**Comment by fekaputra** [comment]
Hi Doron,

I am not much of a developer these days, so my estimation could be off, but I think 1-2 week hours should be sufficient - including code refactoring a bit. I already started to do that a few weeks ago, but halted due to work.

best regards,
Fajar

Sent from my iPhone

On 25.05.2018, at 10:13, Doron Goldfarb <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

thanks for your quick reply, of course I understand the circumstances. How much effort do you think would it be to update the code accordingly?

Kind regards,
Doron

**Comment by fekaputra** [comment]
This issue is now resolved - thanks to the latest PR.
